version: "3.8"

services:
  app:
    build: docker/php
    volumes:
      - ./:/app
    depends_on:
      - db

  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 8000:80
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0.28
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_DATABASE: "tgstat-test"
      MYSQL_ROOT_PASSWORD: "root"